-- PostgreSQL
CREATE SCHEMA IF NOT EXISTS FNC;

CREATE TABLE IF NOT EXISTS FNC.FNC_CUSTOMER_USER (
  ID BIGINT PRIMARY KEY,
  USERNAME VARCHAR(50),
  USEREMAIL VARCHAR(50),
  PASSWORD VARCHAR(50),
  NAME VARCHAR(50),
  SURNAME VARCHAR(50),
  CREATEDATE BIGINT,   -- epoch millis (matches Java Long)
  STATUS INTEGER,
  STATE INTEGER
);

INSERT INTO FNC.FNC_CUSTOMER_USER
  (ID, USERNAME, USEREMAIL, PASSWORD, NAME, SURNAME, CREATEDATE, STATUS, STATE)
VALUES
  (1, 'jdoe', 'jdoe@example.com', 'P@ssw0rd!', 'John', 'Doe', 1730256000000, 1, 1);

INSERT INTO FNC.FNC_CUSTOMER_USER
  (ID, USERNAME, USEREMAIL, PASSWORD, NAME, SURNAME, CREATEDATE, STATUS, STATE)
VALUES
  (2, 'asmith', 'asmith@example.com', 'S3cret123', 'Alice', 'Smith', 1730342400000, 1, 1);

INSERT INTO FNC.FNC_CUSTOMER_USER
  (ID, USERNAME, USEREMAIL, PASSWORD, NAME, SURNAME, CREATEDATE, STATUS, STATE)
VALUES
  (3, 'bking', 'bking@example.com', 'MyPwd!456', 'Bob', 'King', 1730428800000, 0, 1);

CREATE USER appuser WITH PASSWORD 'test123';
CREATE SCHEMA IF NOT EXISTS fnc;
GRANT USAGE ON SCHEMA fnc TO appuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fnc TO appuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA fnc GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appuser;
